"""
Main entry point — runs the full analysis pipeline:
    1. Generate dataset
    2. Clean data
    3. Exploratory Data Analysis
    4. Visualizations
    5. Save business insights report
"""

import os
import sys
import pandas as pd

# ── Ensure project root is on PATH ──────────────────────────────────────────
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, PROJECT_ROOT)

from src.data_generator import generate_dataset, OUTPUT_PATH
from src.data_cleaning import DataCleaner
from src.eda import EDAEngine
from src.visualizations import DashboardVisualizer
from src.cohort_analysis import CohortAnalyzer
from src.price_elasticity import PriceElasticityAnalyzer


def write_insights_report(answers: dict, output_dir: str, cohort_insights: dict, 
                          optimal_pricing: pd.DataFrame):
    """Write business insights to a markdown file."""
    path = os.path.join(output_dir, "reports", "business_insights.md")
    os.makedirs(os.path.dirname(path), exist_ok=True)

    with open(path, "w", encoding="utf-8") as f:
        f.write("# 📊 Business Insights Report\n\n")
        f.write("*Auto-generated by the analysis pipeline.*\n\n")
        f.write("---\n\n")
        
        # Original business questions
        f.write("## Part 1: Core Business Analysis\n\n")
        for i, (question, answer) in enumerate(answers.items(), 1):
            f.write(f"### {i}. {question}\n\n")
            f.write(f"**Finding:** {answer}\n\n")
        
        # Cohort insights
        f.write("---\n\n## Part 2: Cohort & Retention Insights\n\n")
        for key, value in cohort_insights.items():
            f.write(f"- **{key.replace('_', ' ').title()}:** {value}\n")
        
        # Pricing insights
        f.write("\n---\n\n## Part 3: Price Optimization Recommendations\n\n")
        for idx, row in optimal_pricing.iterrows():
            f.write(f"### {row['category']}\n\n")
            f.write(f"- Current Average Price: ${row['current_avg_price']}\n")
            f.write(f"- Price Elasticity: {row['price_elasticity']}\n")
            f.write(f"- **Optimal Price:** ${row['optimal_price']}\n")
            f.write(f"- **Potential Revenue Increase:** {row['potential_revenue_increase']}\n")
            f.write(f"- **Strategy:** {row['strategy']}\n\n")
        
        # Strategic recommendations
        f.write("---\n\n## 📌 Strategic Recommendations\n\n")
        f.write("1. **Double down on Electronics & Clothing** — they drive "
                "55%+ of revenue. Expand SKU depth.\n")
        f.write("2. **Invest in West & East regions** — higher AOV indicates "
                "stronger purchasing power.\n")
        f.write("3. **Launch a Premium loyalty program** — Premium customers "
                "spend significantly more per order.\n")
        f.write("4. **Cap discounts at 20%** — steeper discounts erode "
                "margins without proportional volume gains.\n")
        f.write("5. **Ramp up marketing spend in May–July and Oct–Dec** — "
                "seasonal peaks offer the best ROAS.\n")
        f.write("6. **Implement cohort-based retention programs** — focus on "
                "month 1-3 retention to improve CLV.\n")
        f.write("7. **Optimize pricing by category** — use elasticity-based pricing "
                "to maximize revenue and margins.\n")
    
    print(f"\n📝 Business insights report saved → {path}")


def main():
    print("\n" + "█" * 60)
    print("  🛒 E-COMMERCE SALES ANALYSIS PIPELINE")
    print("█" * 60)

    # ── Step 1: Generate dataset ─────────────────────────────────────────
    print("\n📦 STEP 1 — Generating dataset...")
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    raw_df = generate_dataset()
    raw_df.to_csv(OUTPUT_PATH, index=False)
    print(f"   ✅ {len(raw_df):,} rows saved to {OUTPUT_PATH}")

    # ── Step 2: Clean data ───────────────────────────────────────────────
    print("\n🧹 STEP 2 — Cleaning data...")
    cleaner = DataCleaner()
    clean_df = cleaner.run()
    print(cleaner.get_cleaning_report())

    # ── Step 3: EDA ──────────────────────────────────────────────────────
    print("\n🔍 STEP 3 — Exploratory Data Analysis...")
    eda = EDAEngine(clean_df)
    results = eda.run_full_eda()

    # ── Step 4: Visualizations ───────────────────────────────────────────
    print("\n🎨 STEP 4 — Creating visualizations...")
    viz = DashboardVisualizer(clean_df, results)
    viz.generate_all()

    # ── Step 5: Cohort Analysis ──────────────────────────────────────────
    print("\n👥 STEP 5 — Running cohort analysis...")
    cohort_analyzer = CohortAnalyzer(clean_df)
    cohort_results = cohort_analyzer.run_full_analysis()

    # ── Step 6: Price Elasticity Analysis ────────────────────────────────
    print("\n💹 STEP 6 — Analyzing price elasticity...")
    elasticity_analyzer = PriceElasticityAnalyzer(clean_df)
    elasticity_results = elasticity_analyzer.run_full_analysis()

    # ── Step 7: Business report ──────────────────────────────────────────
    print("\n📝 STEP 7 — Writing insights report...")
    write_insights_report(
        results["business_answers"],
        PROJECT_ROOT,
        cohort_results["insights"],
        elasticity_results["optimal_pricing"]
    )

    # ── Done ─────────────────────────────────────────────────────────────
    print("\n" + "█" * 60)
    print("  ✅ PIPELINE COMPLETE — ALL OUTPUTS SAVED")
    print("█" * 60)
    print(f"""
    📁 Outputs:
       • data/ecommerce_sales_raw.csv      (raw data)
       • data/ecommerce_sales_clean.csv    (cleaned data)
       • outputs/plots/*.png               (8 visualizations)
       • reports/business_insights.md      (findings & recommendations)
       
    📊 Analyses Completed:
       ✅ Exploratory Data Analysis (EDA)
       ✅ Cohort Analysis & Retention Insights
       ✅ Price Elasticity & Optimization
    """)


if __name__ == "__main__":
    main()
